/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_bingluen_heyyzu_constant_YZUSecret */

#ifndef _Included_tw_bingluen_heyyzu_constant_YZUSecret
#define _Included_tw_bingluen_heyyzu_constant_YZUSecret
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_bingluen_heyyzu_constant_YZUSecret
 * Method:    getUsername
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_bingluen_heyyzu_constant_YZUSecret_getUsername
  (JNIEnv *, jclass);

/*
 * Class:     tw_bingluen_heyyzu_constant_YZUSecret
 * Method:    getPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_bingluen_heyyzu_constant_YZUSecret_getPassword
  (JNIEnv *, jclass);

/*
 * Class:     tw_bingluen_heyyzu_constant_YZUSecret
 * Method:    getAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_bingluen_heyyzu_constant_YZUSecret_getAppId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
